version: '3'
services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_USER: example-user
      MYSQL_PASSWORD: my_cool_secret
      MYSQL_DATABASE: example-database
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/db/init:/docker-entrypoint-initdb.d

  node-service:
    build: ./docker/api
    environment:
      DB_HOST: db
      DB_USERNAME: example-user
      DB_PASSWORD: my_cool_secret
      DB_DATABASE: example-database
    ports:
      - "3000"
    depends_on:
      - db

  nginx:
    build: ./docker/nginx
    ports:
      - "8080:80"
    depends_on:
      - node-service

volumes:
  db_data:
    driver: local